baseURL = "https://ttl0.sh/"
languageCode = "en-us"
title = "ttl0"
theme = "re-terminal"

[params]
  themeColor = "red"
  customLogo = "ttl0.sh"
  readingTime = true
  minuteReadingTime = "min read"
  words = "words"

[params.meta]
  favicon = false

[taxonomies]
  tag = "tags"
  category = "categories"

[[menu.main]]
  name = "Home"

  url  = "/"
  weight = 1

[[menu.main]]
  name = "Projects"
  url  = "/projects/"
  weight = 2

[[menu.main]]
  name = "Blog"
  url  = "/posts/"
  weight = 3

[[menu.main]]
  name = "About"
  url  = "/about/"
  weight = 4
